# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_theuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheUser',
            new_name='Profile',
        ),
    ]
