# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_profile_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fails',
            field=models.IntegerField(default=0),
        ),
    ]
