# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_profile_fails'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invited',
            field=models.BooleanField(default=False),
        ),
    ]
