# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0002_trip_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
